# Permalinks
permalink:           pretty

# Setup
title:               Luke
url:                 http://l-warlok.github.io/
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Luke Warlik
  url:               https://twitter.com/luke_warlik
  email:             lukewarlik@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/L-Warlok/l-warlok.github.io

# Gems
gems:
  - jekyll-gist

# Pages
about:			/about/index.html
blog:			/blog/index.html
