# Permalinks
permalink:           /blog/:title/

# Setup
title:               Luke
url:                 http://l-warlok.github.io/
baseurl:             ""
analytics_id: UA-75819191-1
excerpt_separator: ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Luke Warlik
  url:               https://twitter.com/luke_warlik
  email:             lukewarlik@gmail.com
linkdin:             https://au.linkedin.com/in/lukewarlik
fayboo:              https://facebook.com/lukewarlik
twitter:             https://twitter.com/luke_warlik

# Custom vars
version:             2.0.0
github:            https://github.com/L-Warlok
repo:              https://github.com/L-Warlok/l-warlok.github.io

# Gems
gems:
  - jekyll-gist


collections:
 homePages:
  output: true
  permalink: /:title/
 projects: 
  output: true
  permalink: /:title/
